/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import dominio.*;
import javax.swing.JOptionPane;
import negocio.*;
/**
 *
 * @author marco
 */
public class registrarMedicamentoFrm extends javax.swing.JFrame {

    Usuario usuarioActual;
    MedicamentoBo medicamentoBo;
    /**
     * Creates new form registrarMedicamentoFrm
     */
    public registrarMedicamentoFrm() {
        initComponents();
    }
    public registrarMedicamentoFrm(Usuario usuarioActual) {
        medicamentoBo = new MedicamentoBo();
        this.usuarioActual = usuarioActual;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbln = new javax.swing.JLabel();
        labeld = new javax.swing.JLabel();
        lblf = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtDosis = new javax.swing.JTextField();
        txtFrecuencia = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalir.setBackground(new java.awt.Color(255, 51, 51));
        btnSalir.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        btnRegistrar.setBackground(new java.awt.Color(0, 0, 255));
        btnRegistrar.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 330, 140, 40));

        jLabel1.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("MyMedicine");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 280, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, -1, 420));

        lbln.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 12)); // NOI18N
        lbln.setForeground(new java.awt.Color(0, 0, 0));
        lbln.setText("Nombre del medicamento:");
        jPanel1.add(lbln, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, 30));

        labeld.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 12)); // NOI18N
        labeld.setForeground(new java.awt.Color(0, 0, 0));
        labeld.setText("Dosis(ml): ");
        jPanel1.add(labeld, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 70, -1));

        lblf.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 12)); // NOI18N
        lblf.setForeground(new java.awt.Color(0, 0, 0));
        lblf.setText("Frecuencia(Minutos):");
        jPanel1.add(lblf, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 130, -1));

        txtNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 12)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 210, -1));

        txtDosis.setBackground(new java.awt.Color(255, 255, 255));
        txtDosis.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 12)); // NOI18N
        txtDosis.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtDosis, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 90, -1));

        txtFrecuencia.setBackground(new java.awt.Color(255, 255, 255));
        txtFrecuencia.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 12)); // NOI18N
        txtFrecuencia.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtFrecuencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 90, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        MainAppFrm frame = new MainAppFrm();
        this.dispose();
        frame.setVisible(true);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        
        String nombre = txtNombre.getText();
        float dosis = Float.parseFloat(txtDosis.getText());
        float frecuencia = Float.parseFloat(txtFrecuencia.getText());
        Medicamento medicamentoNuevo = new Medicamento(nombre, dosis, frecuencia, this.usuarioActual);
        Medicamento medicamento = medicamentoBo.insertar(medicamentoNuevo);
        this.usuarioActual.getMedicamentos().add(medicamento);
        
        if(medicamento != null){
            mostrarNotificacion("Medicamento Registrado");
            this.dispose();
            MainAppFrm frame = new MainAppFrm(this.usuarioActual);
            frame.setVisible(true);
        }else{
            mostrarNotificacion("Error al registar medicamento");
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void mostrarNotificacion(String mensaje) {
        JOptionPane.showMessageDialog(null, mensaje, "Notificación", JOptionPane.INFORMATION_MESSAGE);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registrarMedicamentoFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registrarMedicamentoFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registrarMedicamentoFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registrarMedicamentoFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registrarMedicamentoFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labeld;
    private javax.swing.JLabel lblf;
    private javax.swing.JLabel lbln;
    private javax.swing.JTextField txtDosis;
    private javax.swing.JTextField txtFrecuencia;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
